Check return value of newNativeSocket before use
In newAsyncNativeSocket the function setBlocking is called on the result
of newNativeSocket regardless of whether the socket returned is valid or
not. If an invalid socket is returned then the error:

    Error: unhandled exception: Bad file descriptor [Exception]

is thrown.

Check the return value first so that a more appropriate error is
raised.