guards.nim:sameTree(): handle uint literals correctly
The compiler crashes in sameTree() with:

    guards.nim(445) sameTree
    ast.nim(1026) len
    fatal.nim(39) sysFatal
    Error: unhandled exception: sons [FieldError]

when compiling the following code:

    proc f(): array[288, uint16] =
      for i in 0'u16 ..< 144'u16:
        result[0'u16 + i] = i
      for i in 0'u16 ..< 8'u16:
        result[0'u16 + i] = i

This is because uint literals (with kind `nkUIntLit..nkUInt64Lit`) are
leaf nodes that should be compared by their intVal, but sameTree()
tried to handle them like non-leaf nodes, causing the crash. Fix this.