fix test failures in subexes due to missing trailing whitespace
FAIL: subexes.nim
Test "lib/pure/subexes.nim" in category "lib"
Failure: reExitcodesDiffer
Expected:
exitcode: 0
Gotten:
exitcode: 1
Output:
Traceback (most recent call last)
subexes.nim(385)         subexes
system.nim(3335)         raiseAssert
system.nim(2531)         sysFatal
Error: unhandled exception: "$#($\', \'10c\'\x0A    \'{#..})" % ["doAssert", "longishA", "longish"] ==